spring.application.name=fruitapp

spring.profiles.active=dev

#sql
spring.datasource.url=jdbc:postgresql://localhost:5432/fruitapp
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver
#hibernate/jpa
spring.jpa.hibernate.ddl-auto=create

#PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

#server properties
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

#spring properties
spring.messages.encoding=UTF-8
spring.banner.charset=UTF-8
